### ISSUE TITLE
Tests are failing with merge mismatch

### ISSUE THREAD

**Issue by dkuschmierz** [matepek/vscode-catch2-test-adapter#115]
**Before you file an issue, please check the [README.md](https://github.com/matepek/vscode-catch2-test-adapter#known-issues)'s known issues section.**

**Describe the bug** (A clear and concise description of what the bug is.)
When running test (sometimes even after scanning) the tests are marked as failing with the following error profiling: /external/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.gcda: Merge mismatch for function 1

**To Reproduce** (Steps to reproduce the behavior:)

**Expected behavior** (A clear and concise description of what you expected to happen.)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- Extension Version [e.g. 22] 2.6.4
- VS Code Version [e.g. 22] 1.36.1
- Catch2/Google Test Version 1.8
- OS Type and Version Win 10

**Log** (Attach log. (optional, Set: `catch2TestExplorer.logfile` and reproduce the bug.) _Warning_: Log probably contains file and test names too.)

**Additional context** Add any other context about the problem here.

**Comment by dkuschmierz** [comment]
Which gcda/gcno file is the tool parsing? From the error it points to /external/googletest/googletest/CMakeFiles/gtest.dir/src/ 

But i would expect that the tool is parsing the gcno files from the folder where the test-exe folder is located

**Comment by NINI1988** [comment]
I have a similar issue while using code coverage `gcc --coverage`.

Everything works fine until i set:
"catch2TestExplorer.workerMaxNumber": 2,

I guess it happens when multiple test application run in parallel and modifying the same coverage files?

```
profiling:D:\test3\cLogTest/Log.gcda:Data file mismatch - some data files may have been concurrently updated without locking support
```

**Comment by matepek** [comment]
Thanks @NINI1988 for your comment.
I'm pretty sure that you are right.

So basically what happens is that there are more executables built for generating coverage information. My extension runs them parallelly and they mess up the gcda files.

As it is said "catch2TestExplorer.workerMaxNumber": 1 should fix it.
BTW: that is why I ask for the log, to check these parameters.

Let me know if it does not solve it.

**Comment by matepek** [comment]
And here comes a feature question: Is there any need to set up a limit for one executable set (by pattern). I mean 
```
"catch2TestExplorer.executables": [
  {"pattern":"gtest*", workerMaxNumber:1 },
  {"pattern":"catch2test*", workerMaxNumber:4 }
],
"catch2TestExplorer.workerMaxNumber": 5,
```
This would allow to run maximum 5 executables parallel.
I haven't developed it because I haven't found any practical use case until now.

**Comment by dkuschmierz** [comment]
I had the same in mind, but overseen the workerMaxNumber configuration. Anyway, if I set the workerMaxNumber to 1 the problem still persists.

I saw your request for the lock, but unfortunately I'm working on productive code and I'm not allowed to share the log-files. Can you reproduce the problem? If not, I'll look if I can set up a little project at home.

Here is short snippet from the log (blackened)

`[2019-08-02 06:08:59.461] [WARN] [at _reloadGoogleTests.c2fs.spawnAsync.then (C:\Users\<USER>\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.4\out\src\GoogleTestSuiteInfo.js:135:34)] reloadChildren -> googleTestListOutput.stderr:  { pid: 16636,
  output:
   [ null,
     'Running main() from gmock_main.cc\r\nModuleATest.\r\n  <TEST_FUNCTIONS>',
     'profiling:<LOCATION>\\build\\tests/external/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.gcda:Merge mismatch for function 60\r\nprofiling:<LOCATION>\\build\\tests/external/googletest/googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.gcda:Data file mismatch - some data files may have been concurrently updated without locking support\r\nprofiling:<LOCATION>\\build\\tests/external/googletest/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.gcda:Merge mismatch for function 0\r\n' ],
  stdout:
   'Running main() from gmock_main.cc\r\n<TEST_FUNCTIONS>',
  stderr:
   'profiling:<LOCATION>\\build\\tests/external/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.gcda:Merge mismatch for function 60\r\nprofiling:<LOCATION>\\build\\tests/external/googletest/googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.gcda:Data file mismatch - some data files may have been concurrently updated without locking support\r\nprofiling:<LOCATION>\\build\\tests/external/googletest/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.gcda:Merge mismatch for function 0\r\n',
  status: 0,
  signal: null,
  error: undefined,
  closed: true }`

**Comment by matepek** [comment]
Hm.. let me check something... 
(a minutes later)
Yes! So it turned out that the test scanning can run parallel. Can you imagine that your gcda become dirty while running the executables to list the tests?
I will create a build where the workerMaxNumber effects on the scanner logic too.

**Comment by NINI1988** [comment]
I read that coverage had a locking support for those files, but the locking is used from the operating system. And the locking is only working for different processes but not für different threads.
How do you start the applications in parallel?
Maybe it's a hint?

**Comment by dkuschmierz** [comment]
Yes, I tested to run a single Test with the --gtest_list_tests flag and I get the error too. Afterwards I removed the flags -fprofile-arcs -ftest-coverage and then it works. It also works if i don't set the maxWorkersFlag

**Comment by matepek** [comment]
@NINI1988 : (in case you were talking to me :) )
NodeJs does. I am using the [child_process.spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options). Naturally I have no control over the threads but the processes.

@dkuschmierz 
I guess you have to clean those corrupted files before you trying again.(?)
What should work is when you set only one test exe at `executables`. Would you try that for me?

> It also works if i don't set the maxWorkersFlag

Not setting or setting it to `1` have the same effect. So probably you were just lucky.

**Comment by dkuschmierz** [comment]
Yes you're right. If I only set one executable it is working

**Comment by NINI1988** [comment]
I made a test:
I can run all tests (5 executables) with workerMaxNumber=5 with no problem.
But when I click reload tests button also with workerMaxNumber=1, it crashes.

So i guess the listing is the problem.

**Comment by matepek** [comment]
A modified build will be released soon. If that is the problem, it should be solved.

**Comment by matepek** [comment]
@NINI1988 If you have a minute...

You said:

> I can run all tests (5 executables) with workerMaxNumber=5 with no problem.
> But when I click reload tests button also with workerMaxNumber=1, it crashes.

and 

> I read that coverage had a locking support for those files,

The first one seem weird to me. In the perspective of the coverage I think the executable cannot distinguish between the scanning and the test running calls. (The file is instrumented at build time in a general way)
Following my thought, "locking support" should work for both cases, don't you think?

So you might also were lucky. ?

**Comment by matepek** [comment]
market research question for @dkuschmierz :
I've noticed that you are using gtest-adapter extension too. Would you tell me why you are using 2 extensions for the same purpose?

**Comment by NINI1988** [comment]
Maybe I had luck, but I restarted it many times. 

I can retry it next Tuesday at work, where I have real test applications.

Or is there a difference in executing listing and executing?

**Comment by matepek** [comment]
Released, please verify in version 2.6.5.

> Or is there a difference in executing listing and executing?

Nah, the exec called with different arguments, but nothing else..

**Comment by dkuschmierz** [comment]
> market research question for @dkuschmierz :
I've noticed that you are using gtest-adapter extension too. Would you tell me why you are using 2 extensions for the same purpose?
I only tried to find the right extension for my needs. But it does not automatically scans the tests, so it's no option

**Comment by dkuschmierz** [comment]
> Released, please verify in version 2.6.5.
> 
> > Or is there a difference in executing listing and executing?
> 
> Nah, the exec called with different arguments, but nothing else..

Unfortunately the problem still persists on my side with the 2.6.5 release :-/

**Comment by matepek** [comment]
@dkuschmierz That is weird..
Please search in the log for line "workerMaxNumber..."

Also, have you cleaned up your corrupted files? Restarted your computer? Also unplugging and replugging the printer couldn't do any harm. :)

**Comment by dkuschmierz** [comment]
And I noticed the following:

1. Cleaned my project
2. Build all
3. Ran myTest.exe in console -> all fine
4. Opened VSCode with your extension
5. Tried to run -> fails
6. Closed VSCode
7. Ran myTest.exe in console again -> get error gtest-all.cc.gcda:Merge mismatch for function 1643

**Comment by matepek** [comment]
I guess step num.5 was preceeded by num 4.5 which was the test discovery. So it is discovered the  executables now, not like before. Before there were a problem with that, right?

**Comment by NINI1988** [comment]
The new version does not change anything.
There is now log for workerMaxNumber. Or is the log hidden somewhere?

**Comment by matepek** [comment]
:(

I guess you set the `catch2TestExplorer.logpanel`. There should be in the extension's output window. (a different one, not where are the test output)

It has to be there...

VSCode has to be reloaded after the update. (Sorry for mentioning, but I am running out of ideas :) )

**Comment by NINI1988** [comment]
Is it maybe possible that only the parsing failes?

On the console i get with: ./UNIT_TEST.exe --gtest_list_tests
```
TEST_IMPL.
  LOG_U16_U16
  cLogGeneric
  bitFields
profiling:D:\test3\cLogTest/Log.gcda:Data file mismatch - some data files may have been concurrently updated without locking support
```
And with: ./UNIT_TEST.exe
```
...
[       OK ] TEST_IMPL.bitFields (1 ms)
[----------] 11 tests from TEST_IMPL (12 ms total)

[----------] Global test environment tear-down
[==========] 11 tests from 1 test suite ran. (14 ms total)
[  PASSED  ] 11 tests.
profiling:D:\test3\cLogTest/Log.gcda:Data file mismatch - some data files may have been concurrently updated without locking support
```

**Comment by NINI1988** [comment]
```
[2019-08-02 10:42:32.566] [INFO] [at new TestAdapter (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestAdapter.js:32:19)] info: { uri:
   m {
     scheme: 'file',
     authority: '',
     path: '/D:/test3/cLogTest',
     query: '',
     fragment: '',
     _formatted: 'file:///d%3A/test3/cLogTest',
     _fsPath: 'd:\\test3\\cLogTest' },
  name: 'cLogTest',
  index: 0 } win32 v10.11.0 { http_parser: '2.8.0',
  node: '10.11.0',
  v8: '6.9.427.31-electron.0',
  uv: '1.23.0',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '69',
  nghttp2: '1.33.0',
  napi: '3',
  openssl: '1.1.0',
  icu: '62.2',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2019a' } 1.36.1 { key: 'catch2TestExplorer.3',
  defaultValue: undefined,
  globalValue: undefined,
  workspaceValue: undefined,
  workspaceFolderValue: undefined }
[2019-08-02 10:42:32.567] [INFO] [at TestAdapter._getRetireDebounceTime (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestAdapter.js:443:19)] retireDebounceTimeMilisec: 1000
[2019-08-02 10:42:32.567] [INFO] [at TestAdapter._getDefaultExecWatchTimeout (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestAdapter.js:438:19)] defaultWatchTimeoutSec: 10000
[2019-08-02 10:42:32.567] [INFO] [at TestAdapter._getRetireDebounceTime (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestAdapter.js:443:19)] retireDebounceTimeMilisec: 1000
[2019-08-02 10:42:32.567] [INFO] [at TestAdapter._getDefaultExecRunningTimeout (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestAdapter.js:448:19)] defaultRunningTimeoutSec: 600
[2019-08-02 10:42:32.568] [INFO] [at TestAdapter._getWorkerMaxNumber (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestAdapter.js:430:19)] workerMaxNumber: 1
[2019-08-02 10:42:32.568] [INFO] [at TestAdapter.load (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestAdapter.js:182:19)] load called
[2019-08-02 10:42:32.568] [INFO] [at load._mainTaskQueue.then (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestAdapter.js:188:23)] load started
[2019-08-02 10:42:32.569] [INFO] [at TestAdapter._getExecutables (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestAdapter.js:469:19)] executables: [ './*_TEST*.exe' ]
[2019-08-02 10:42:32.569] [INFO] [at TestExecutableInfo.load (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestExecutableInfo.js:32:26)] pattern { isAbsolute: false,
  absPattern: 'd:\\test3\\cLogTest\\*_TEST*.exe',
  relativeToWs: '*_TEST*.exe',
  isPartOfWs: true,
  relativeToWsPosix: '*_TEST*.exe' }
[2019-08-02 10:42:32.776] [INFO] [at TestExecutableInfo.load (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestExecutableInfo.js:62:30)] Checking file for tests: d:\test3\cLogTest\UNIT_TEST.exe
[2019-08-02 10:42:32.776] [INFO] [at TestExecutableInfo.load (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestExecutableInfo.js:62:30)] Checking file for tests: d:\test3\cLogTest\UNIT_TEST2.exe
[2019-08-02 10:42:32.776] [INFO] [at TestExecutableInfo.load (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestExecutableInfo.js:62:30)] Checking file for tests: d:\test3\cLogTest\UNIT_TEST3.exe
[2019-08-02 10:42:32.777] [INFO] [at TestExecutableInfo.load (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestExecutableInfo.js:62:30)] Checking file for tests: d:\test3\cLogTest\UNIT_TEST4.exe
[2019-08-02 10:42:32.777] [INFO] [at TestExecutableInfo.load (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestExecutableInfo.js:62:30)] Checking file for tests: d:\test3\cLogTest\UNIT_TEST5.exe
[2019-08-02 10:42:32.893] [INFO] [at GoogleTestSuiteInfo._reloadChildren (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\GoogleTestSuiteInfo.js:27:26)] reloadChildren UNIT_TEST2.exe
[2019-08-02 10:42:33.025] [WARN] [at _reloadGoogleTests.c2fs.spawnAsync.then (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\GoogleTestSuiteInfo.js:135:34)] reloadChildren -> googleTestListOutput.stderr:  { pid: 11236,
  output:
   [ null,
     'TEST_IMPL.\r\n  LOB_ARGS\r\n  LOG_COUNT_ARGUMENTS\r\n  LOG_GET_MAX_END_OF_STRING\r\n  LOG_ERROR_NONE\r\n  LOG_ERROR_NONE_LongFunctionName\r\n  test_LOG_ASSERT_EQ\r\n  testStringDataSpace\r\n  LOG_FROM_C_AND_MACRO\r\n  LOG_U16_U16\r\n  cLogGeneric\r\n  bitFields\r\n',
     'profiling:D:\\test3\\cLogTest/main.gcda:Data file mismatch - some data files may have been concurrently updated without locking support\r\n' ],
  stdout:
   'TEST_IMPL.\r\n  LOB_ARGS\r\n  LOG_COUNT_ARGUMENTS\r\n  LOG_GET_MAX_END_OF_STRING\r\n  LOG_ERROR_NONE\r\n  LOG_ERROR_NONE_LongFunctionName\r\n  test_LOG_ASSERT_EQ\r\n  testStringDataSpace\r\n  LOG_FROM_C_AND_MACRO\r\n  LOG_U16_U16\r\n  cLogGeneric\r\n  bitFields\r\n',
  stderr:
   'profiling:D:\\test3\\cLogTest/main.gcda:Data file mismatch - some data files may have been concurrently updated without locking support\r\n',
  status: 0,
  signal: null,
  error: undefined,
  closed: true }
[2019-08-02 10:42:33.025] [INFO] [at GoogleTestSuiteInfo._reloadChildren (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\GoogleTestSuiteInfo.js:27:26)] reloadChildren UNIT_TEST.exe
[2019-08-02 10:42:33.195] [WARN] [at _reloadGoogleTests.c2fs.spawnAsync.then (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\GoogleTestSuiteInfo.js:135:34)] reloadChildren -> googleTestListOutput.stderr:  { pid: 12000,
  output:
   [ null,
     'TEST_IMPL.\r\n  LOB_ARGS\r\n  LOG_COUNT_ARGUMENTS\r\n  LOG_GET_MAX_END_OF_STRING\r\n  LOG_ERROR_NONE\r\n  LOG_ERROR_NONE_LongFunctionName\r\n  test_LOG_ASSERT_EQ\r\n  testStringDataSpace\r\n  LOG_FROM_C_AND_MACRO\r\n  LOG_U16_U16\r\n  cLogGeneric\r\n  bitFields\r\n',
     'profiling:D:\\test3\\cLogTest/main.gcda:Data file mismatch - some data files may have been concurrently updated without locking support\r\n' ],
  stdout:
   'TEST_IMPL.\r\n  LOB_ARGS\r\n  LOG_COUNT_ARGUMENTS\r\n  LOG_GET_MAX_END_OF_STRING\r\n  LOG_ERROR_NONE\r\n  LOG_ERROR_NONE_LongFunctionName\r\n  test_LOG_ASSERT_EQ\r\n  testStringDataSpace\r\n  LOG_FROM_C_AND_MACRO\r\n  LOG_U16_U16\r\n  cLogGeneric\r\n  bitFields\r\n',
  stderr:
   'profiling:D:\\test3\\cLogTest/main.gcda:Data file mismatch - some data files may have been concurrently updated without locking support\r\n',
  status: 0,
  signal: null,
  error: undefined,
  closed: true }
[2019-08-02 10:42:33.195] [INFO] [at GoogleTestSuiteInfo._reloadChildren (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\GoogleTestSuiteInfo.js:27:26)] reloadChildren UNIT_TEST4.exe
[2019-08-02 10:42:33.330] [WARN] [at _reloadGoogleTests.c2fs.spawnAsync.then (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\GoogleTestSuiteInfo.js:135:34)] reloadChildren -> googleTestListOutput.stderr:  { pid: 6156,
  output:
   [ null,
     'TEST_IMPL.\r\n  LOB_ARGS\r\n  LOG_COUNT_ARGUMENTS\r\n  LOG_GET_MAX_END_OF_STRING\r\n  LOG_ERROR_NONE\r\n  LOG_ERROR_NONE_LongFunctionName\r\n  test_LOG_ASSERT_EQ\r\n  testStringDataSpace\r\n  LOG_FROM_C_AND_MACRO\r\n  LOG_U16_U16\r\n  cLogGeneric\r\n  bitFields\r\n',
     'profiling:D:\\test3\\cLogTest/main.gcda:Data file mismatch - some data files may have been concurrently updated without locking support\r\n' ],
  stdout:
   'TEST_IMPL.\r\n  LOB_ARGS\r\n  LOG_COUNT_ARGUMENTS\r\n  LOG_GET_MAX_END_OF_STRING\r\n  LOG_ERROR_NONE\r\n  LOG_ERROR_NONE_LongFunctionName\r\n  test_LOG_ASSERT_EQ\r\n  testStringDataSpace\r\n  LOG_FROM_C_AND_MACRO\r\n  LOG_U16_U16\r\n  cLogGeneric\r\n  bitFields\r\n',
  stderr:
   'profiling:D:\\test3\\cLogTest/main.gcda:Data file mismatch - some data files may have been concurrently updated without locking support\r\n',
  status: 0,
  signal: null,
  error: undefined,
  closed: true }
[2019-08-02 10:42:33.330] [INFO] [at GoogleTestSuiteInfo._reloadChildren (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\GoogleTestSuiteInfo.js:27:26)] reloadChildren UNIT_TEST3.exe
[2019-08-02 10:42:33.473] [WARN] [at _reloadGoogleTests.c2fs.spawnAsync.then (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\GoogleTestSuiteInfo.js:135:34)] reloadChildren -> googleTestListOutput.stderr:  { pid: 992,
  output:
   [ null,
     'TEST_IMPL.\r\n  LOB_ARGS\r\n  LOG_COUNT_ARGUMENTS\r\n  LOG_GET_MAX_END_OF_STRING\r\n  LOG_ERROR_NONE\r\n  LOG_ERROR_NONE_LongFunctionName\r\n  test_LOG_ASSERT_EQ\r\n  testStringDataSpace\r\n  LOG_FROM_C_AND_MACRO\r\n  LOG_U16_U16\r\n  cLogGeneric\r\n  bitFields\r\n',
     'profiling:D:\\test3\\cLogTest/main.gcda:Data file mismatch - some data files may have been concurrently updated without locking support\r\n' ],
  stdout:
   'TEST_IMPL.\r\n  LOB_ARGS\r\n  LOG_COUNT_ARGUMENTS\r\n  LOG_GET_MAX_END_OF_STRING\r\n  LOG_ERROR_NONE\r\n  LOG_ERROR_NONE_LongFunctionName\r\n  test_LOG_ASSERT_EQ\r\n  testStringDataSpace\r\n  LOG_FROM_C_AND_MACRO\r\n  LOG_U16_U16\r\n  cLogGeneric\r\n  bitFields\r\n',
  stderr:
   'profiling:D:\\test3\\cLogTest/main.gcda:Data file mismatch - some data files may have been concurrently updated without locking support\r\n',
  status: 0,
  signal: null,
  error: undefined,
  closed: true }
[2019-08-02 10:42:33.473] [INFO] [at GoogleTestSuiteInfo._reloadChildren (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\GoogleTestSuiteInfo.js:27:26)] reloadChildren UNIT_TEST5.exe
[2019-08-02 10:42:33.577] [WARN] [at _reloadGoogleTests.c2fs.spawnAsync.then (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\GoogleTestSuiteInfo.js:135:34)] reloadChildren -> googleTestListOutput.stderr:  { pid: 7972,
  output:
   [ null,
     'TEST_IMPL.\r\n  LOB_ARGS\r\n  LOG_COUNT_ARGUMENTS\r\n  LOG_GET_MAX_END_OF_STRING\r\n  LOG_ERROR_NONE\r\n  LOG_ERROR_NONE_LongFunctionName\r\n  test_LOG_ASSERT_EQ\r\n  testStringDataSpace\r\n  LOG_FROM_C_AND_MACRO\r\n  LOG_U16_U16\r\n  cLogGeneric\r\n  bitFields\r\n',
     'profiling:D:\\test3\\cLogTest/main.gcda:Data file mismatch - some data files may have been concurrently updated without locking support\r\n' ],
  stdout:
   'TEST_IMPL.\r\n  LOB_ARGS\r\n  LOG_COUNT_ARGUMENTS\r\n  LOG_GET_MAX_END_OF_STRING\r\n  LOG_ERROR_NONE\r\n  LOG_ERROR_NONE_LongFunctionName\r\n  test_LOG_ASSERT_EQ\r\n  testStringDataSpace\r\n  LOG_FROM_C_AND_MACRO\r\n  LOG_U16_U16\r\n  cLogGeneric\r\n  bitFields\r\n',
  stderr:
   'profiling:D:\\test3\\cLogTest/main.gcda:Data file mismatch - some data files may have been concurrently updated without locking support\r\n',
  status: 0,
  signal: null,
  error: undefined,
  closed: true }
[2019-08-02 10:42:33.577] [INFO] [at load._mainTaskQueue.then._rootSuite.load.then (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestAdapter.js:191:27)] load finished 5

```

**Comment by matepek** [comment]
Thanks again for the logs. It helped, have another clue to investigate..

**Comment by dkuschmierz** [comment]
> I guess step num.5 was preceeded by num 4.5 which was the test discovery. So it is discovered the executables now, not like before. Before there were a problem with that, right?

No, the tests where discovered correctly all the time, but they are marked with the red exclamation mark and "Check the test output message for details", even if I did not run the tests

**Comment by matepek** [comment]
The log helped me to realize that I missed one step, when I detect the type of the test (gtest/catch2). That was run concurrently. See the timestamps:

> [2019-08-02 10:42:32.776] [INFO] [at TestExecutableInfo.load (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestExecutableInfo.js:62:30)] Checking file for tests: d:\test3\cLogTest\UNIT_TEST.exe
> [2019-08-02 10:42:32.776] [INFO] [at TestExecutableInfo.load (C:\Users\NINI\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.6.5\out\src\TestExecutableInfo.js:62:30)] Checking file for tests: d:\test3\cLogTest\UNIT_TEST2.exe

Version 2.6.6 should fix that. Hopefully nothing more left.. 
Thanks for the log again!! 👍

Will be released in a min..

**Comment by dkuschmierz** [comment]
Yes!! Now it's working!
