### ISSUE TITLE
Logging with logpanel or logfile settings doesn't work

### ISSUE THREAD

**Issue by vakokako** [matepek/vscode-catch2-test-adapter#383]
Reopening https://github.com/matepek/vscode-catch2-test-adapter/issues/382

**Describe the bug**

Logging doesn't work, both for `logpanel`, and `logfile`.

**To Reproduce**

1. Set these properties in the folder `settings.json` file:
```json
"testMate.cpp.log.logpanel": true,
"testMate.cpp.log.logfile": "/tmp/testMate.log",
```

2. Reopen the project so that new settings are in effect
3. Open side panel window to see project's tests
4. "/tmp/testMate.log" isn't created, there is no logging window in output for test extension

**Desktop**

- Extension Version: v4.4.1 
- VS Code Version: 1.77.3
- Catch2 / Google Test / DOCTest Version:
- OS Type and Version: Ubuntu 22.04
- Using remote-ssh/docker/wsl?: nope

**Comment by emmenlau** [comment]
Same for me, with a different user account but similar setup of OS and VSCode.

**Comment by emmenlau** [comment]
Also, when I search for `logFile` in the sources, I find the only references in source code in https://github.com/matepek/vscode-catch2-test-adapter/blob/3a0a33681d3591f5c5b64d5b96a459fbcaccc348/test/Common.ts#L184. But there it is actually *excluded* and not *included*. Is it possible that the key `logFile` is even unused? Or am I on the wrong track?

**Comment by matepek** [comment]
That line is not related. This is the one: https://github.com/hbenl/vscode-test-adapter-util/blob/master/src/log.ts#L31
And I can still see the logs both for window and file..

**Comment by matepek** [comment]
It is possible to try an earlier version of the extension or an earlier version of VSCode. that would help I believe.

**Comment by vakokako** [comment]
I tried up to version `4.0.0` and it still didn't work...

**Comment by yi-ge** [comment]
Same for me

**Comment by matepek** [comment]
Installing ubuntu 22 is time consuming..
Do you guys have some issue and would need the log or just would like to see the logs?
Logpanel also nothing? Hard to think what could be the issue...

**Comment by yi-ge** [comment]
I need the log file.

**Comment by matepek** [comment]
Please state your `OS Type and Version`
@yi-ge , @emmenlau

**Comment by yi-ge** [comment]
Windows 11 x86_64
MacOS Arm64 13.5 Beta版(22G5027e)
@matepek

**Comment by matepek** [comment]
Okay so this is a multi platform issue which I cannot reproduce locally.
If someone would like to help me debugging, let me know. We can create a session.
Otherwise one can create a VM in which it is reproducible and share with me. :D

**Comment by matepek** [comment]
Any news on this front? It still works for me.

**Comment by johannes-fischer** [comment]
Also does not work for me on Ubuntu 20.04.

**Comment by matepek** [comment]
@johannes-fischer , In your linked issue you were able to quote log output. Where did you get it if it doesn't work for you?

**Comment by johannes-fischer** [comment]
As I wrote in the linked issue, I only was lucky to get logs sometimes:
> I now sometimes get logs, but unreliably: I only see the logs in the output window early after a vs code restart, after some time the window vanishes from the drop-down list. Also, most of the restarts there are not logs at all.

**Comment by matepek** [comment]
I have just tried enabling the `testMate.cpp.log.logpanel` and the output log-panel is there.

<img width="1139" alt="Image" src="https://github.com/user-attachments/assets/3005f5dd-5797-464e-a926-72b4663ac5e1" />

I have to assume it was a vscode bug which is solved since.

**Comment by lilveg** [comment]
This issue still persists for me on VSCode 1.103.2, TestMate v4.17.3 on Windows 11. I am not able to get anything in the output pane, no log file and no tests detected. It's as if the extension is not running at all.

<img width="280" height="182" alt="Image" src="https://github.com/user-attachments/assets/b9ad9def-ee33-4995-a281-eb4fba678dba" />
